version: '3.8'
services:
  moviepilot:
    container_name: moviepilot
    image: 'jxxghp/moviepilot:latest'
    restart: unless-stopped
    ports:
      - '3001:3001'
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 000
      TZ: Asia/Shanghai
      NGINX_PORT: 3001
      SUPERUSER: 'admin'
      SUPERUSER_PASSWORD: ''
      API_TOKEN: ''
      PROXY_HOST: ''
      DOWNLOAD_PATH: 'F:\下载'
      DOWNLOAD_CATEGORY: true
      DOWNLOAD_SUBTITLE: true
      REFRESH_MEDIASERVER: true
      DOWNLOADER_MONITOR: false
      SCRAP_METADATA: true
      TORRENT_TAG: 'MOVIEPILOT'
      LIBRARY_PATH: '/F/media'
      LIBRARY_CATEGORY: true
      TRANSFER_TYPE: 'link'
      COOKIECLOUD_HOST: ''
      COOKIECLOUD_KEY: ''
      COOKIECLOUD_PASSWORD: ''
      COOKIECLOUD_INTERVAL: 10
      USER_AGENT: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.183'
      MESSAGER: 'telegram'
      TELEGRAM_TOKEN: ''
      TELEGRAM_CHAT_ID: 
      TELEGRAM_USERS: 
      TELEGRAM_ADMINS: 
      DOWNLOADER: 'qbittorrent'
      QB_HOST: '192.168.50.160:8990'
      QB_USER: 'admin'
      QB_PASSWORD: 'adminadmin'
      MEDIASERVER: 'jellyfin'
      MEDIASERVER_SYNC_INTERVAL: 6
      JELLYFIN_HOST: '192.168.50.160:8096'
      JELLYFIN_API_KEY: ''
      AUTH_SITE: 'iyuu'
      IYUU_SIGN: ''
      BIG_MEMORY_MODE: true
    volumes:
      - ./config:/config
      - ./moviepilot:/moviepilot
      - /F:/F