version: "3"
services:
  moviepilot:
    image: jxxghp/moviepilot:latest
    volumes:
      - /volume4/docker/moviepilot:/moviepilot #程序主目录，必选
      - /volume4/docker/moviepilot/config:/config #config 配置文件，必选
      - /volume1/Media1:/volume1/Media1 #媒体库1，因为个人要兼容套件版qb/tr，故需映射/volume1根目录 - 仅供参考
      - /volume2/Media2:/Media2 #媒体库2，只有存量，无需下载，故不需要映射根目录，强迫症可以考虑 - 仅供参考
      - /volume3/Media3:/Media3 #
      - /volume4/Media4:/Media4 #
      - /volume4/docker/nas-tools/config:/nas-tools/config # nt数据库，用于转移历史记录
      - /volume4/@appdata/transmission/torrents:/torrents #tr种子目录，转移和辅钟需要
      - /volume4/@appdata/qBittorrent/qBittorrent_conf/data/BT_backup:/BT_backup #qb种子目录，转移和辅钟需要
      - /volume4/docker/etc/hosts:/etc/hosts   #host文件映射，方便其他容器套用
    environment: 
      - PUID=1026 # 运行程序用户的uid，默认0
      - PGID=100  # 运行程序用户的gid，默认0
      - UMASK=000 # 掩码权限，默认000，可以考虑设置为022
      - MOVIEPILOT_AUTO_UPDATE=true #重启更新，true/false，默认true
      - NGINX_PORT= #WEB服务端口，默认3000，可自行修改，但不能为3001
      - SUPERUSER=  #超级管理员用户名，默认admin，安装后使用该用户登录后台管理界面
      - SUPERUSER_  # 超级管理员初始密码，默认password，建议修改为复杂密码
      - API_TOKEN=moviepilot #API密钥，默认moviepilot，在媒体服务器Webhook、微信回调等地址配置中需要加上?token=该值，建议修改为复杂字符串
      - PROXY_HOST= #网络代理（可选），访问themoviedb需要使用代理访问，格式为http(s)://ip:port
      - TMDB_API_DOMAIN=api.themoviedb.org # TMDB API地址，默认api.themoviedb.org，也可配置为api.tmdb.org或其它中转代理服务地址，能连通即可
#下载目录/开关
      - DOWNLOAD_PATH=/volume1/Media1/downloads1 #下载保存目录，注意：需要将moviepilot及下载器的映射路径保持一致，否则会导致下载文件无法转移 - 仅供参考
      - DOWNLOAD_MOVIE_PATH=/volume1/Media1/downloads1/Movies #电影下载保存目录，必须是DOWNLOAD_PATH的下级路径，不设置则下载到DOWNLOAD_PATH - 仅供参考
      - DOWNLOAD_TV_PATH=/volume1/Media1/downloads1/Tv Shows #电视剧下载保存目录，必须是DOWNLOAD_PATH的下级路径，不设置则下载到DOWNLOAD_PATH - 仅供参考
      - DOWNLOAD_ANIME_PATH=/volume1/Media1/downloads1/Anime #动漫下载保存目录，必须是DOWNLOAD_PATH的下级路径，不设置则下载到DOWNLOAD_PATH - 仅供参考
      - DOWNLOAD_CATEGORY=false #下载二级分类开关，true/false，默认false,开启后会根据配置category.yaml自动在下载目录下建立二级目录分类
      - DOWNLOAD_SUBTITLE=true #下载站点字幕，true/false，默认true
      - REFRESH_MEDIASERVER=true #入库刷新媒体库，true/false，默认true
      - SUBSCRIBE_MODE=spider
      - SUBSCRIBE_RSS_INTERVAL=30
      - SCRAP_METADATA=true #刮削入库的媒体文件，true/false，默认true
      - TORRENT_TAG=MOVIEPILOT #种子标签，默认为MOVIEPILOT，设置后只有MoviePilot添加的下载才会处理，留空所有下载器中的任务均会处理
# 媒体库路径/分类
      - LIBRARY_PATH=/volume1/Media1,/Media2,/Media3,/Media4 #媒体库目录，多个目录使用,分隔 - 仅供参考
      - LIBRARY_MOVIE_NAME=电影 #电影媒体库目录名，默认电影
      - LIBRARY_TV_NAME=电视剧 #电视剧媒体库目录名，默认电视剧
      - LIBRARY_ANIME_NAME=动漫 #动漫媒体库目录名，默认电视剧/动漫
      - LIBRARY_CATEGORY=true # 媒体库二级分类开关，true/false，默认false，开启后会根据配置category.yaml自动在媒体库目录下建立二级目录分类
# 转移方式，支持link/copy/move/softlink
      - TRANSFER_TYPE=link
# CookieCloud服务器配置
      - COOKIECLOUD_HOST=   # CookieCloud服务器地址，格式：http://ip:port，必须配置，否则无法添加站点
      - COOKIECLOUD_KEY=
      - COOKIECLOUD_PASSWORD=
      - COOKIECLOUD_INTERVAL=180  # CookieCloud同步间隔（分钟）
# CookieCloud对应的浏览器UA
      - USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.188 #CookieCloud对应的浏览器UA，可选，设置后可增加连接站点的成功率，同步站点后可以在管理界面中修改
# 消息通知渠道
      - MESSAGER=telegram  # 消息通知渠道，支持 telegram/wechat/slack/synologychat，开启多个渠道时使用,分隔。同时还需要配置对应渠道的环境变量，非对应渠道的变量可删除，推荐使用telegram
# wechat设置项
      - WECHAT_CORPID=  #WeChat企业ID
      - WECHAT_APP_SECRET=  #WeChat应用Secret
      - WECHAT_APP_ID=  #WeChat应用ID
      - WECHAT_TOKEN=  #WeChat消息回调的Token
      - WECHAT_ENCODING_AESKEY=  #WeChat消息回调的EncodingAESKey
      - WECHAT_PROXY= #WeChat代理服务器（后面不要加/）
#telegram设置项
      - TELEGRAM_TOKEN= # Telegram Bot Token
      - TELEGRAM_CHAT_ID= # Telegram Chat ID
      - TELEGRAM_USERS= #Telegram 用户ID，多个使用,分隔，只有用户ID在列表中才可以使用Bot，如未设置则均可以使用Bot
      - TELEGRAM_ADMINS= #Telegram 管理员ID，多个使用,分隔，只有管理员才可以操作Bot菜单，如未设置则均可以操作菜单
#slack设置项：
      - SLACK_OAUTH_TOKEN= #Slack Bot User OAuth Token
      - SLACK_APP_TOKEN= #Slack App-Level Token
      - SLACK_CHANNEL= #Slack 频道名称，默认全体
      - SYNOLOGYCHAT_WEBHOOK= #在Synology Chat中创建机器人，获取机器人传入URL
      - SYNOLOGYCHAT_TOKEN= #SynologyChat机器人令牌
# 下载器
      - DOWNLOADER=qbittorrent #下载器，支持qbittorrent/transmission，QB版本号要求>= 4.3.9，TR版本号要求>= 3.0，同时还需要配置对应渠道的环境变量，非对应渠道的变量可删除，推荐使用qbittorrent
#qbittorrent设置项
      - QB_HOST= #qbittorrent地址，格式：ip:port，https需要添加https://前缀
      - QB_USER= #qbittorrent用户名
      - QB_PASSWORD= #qbittorrent密码
#transmission设置项
      - TR_HOST= #transmission地址，格式：ip:port，https需要添加https://前缀
      - TR_USER= #transmission用户名
      - TR_PASSWORD= #transmission密码
      - DOWNLOADER_MONITOR=true #下载器监控，true/false，默认为true，开启后下载完成时才会自动整理入库
# 媒体服务器配置
      - MEDIASERVER=emby #媒体服务器，支持emby/jellyfin/plex，同时还需要配置对应媒体服务器的环境变量，非对应媒体服务器的变量可删除，推荐使用emby
#emby设置项
      - EMBY_HOST=  # Emby服务器地址，格式：ip:port，https需要添加https://前缀
      - EMBY_API_KEY= # Emby Api Key，在设置->高级->API密钥处生成
#jellyfin设置项
      - JELLYFIN_HOST= #Jellyfin服务器地址，格式：ip:port，https需要添加https://前缀
      - JELLYFIN_API_KEY= #Jellyfin Api Key，在设置->高级->API密钥处生成
#plex设置项
      - PLEX_HOST= #Plex服务器地址，格式：ip:port，https需要添加https://前缀
      - PLEX_TOKEN= #Plex网页Url中的X-Plex-Token，通过浏览器F12->网络从请求URL中获取
      - MEDIASERVER_SYNC_INTERVAL=1 #媒体服务器同步间隔（小时），默认6，留空则不同步
      - MEDIASERVER_SYNC_BLACKLIST= #媒体服务器同步黑名单，多个媒体库名称使用,分割
# 认证站点
      - AUTH_SITE=iyuu  # 认证站点，支持hhclub/audiences/hddolby/zmpt/freefarm/hdfans/wintersakura/leaves/1ptba/icc2022/iyuu
# IYUU登录令牌
      - IYUU_SIGN=  #IYUU登录令牌
# 大内存模式，默认为false，开启后会占用更多的内存，但响应速度会更快
      - BIG_MEMORY_MODE=true 
# 交互搜索自动下载用户ID，使用,分割
      - AUTO_DOWNLOAD_USER=
    restart: on-failure
    network_mode: host
    hostname: moviepilot
    container_name: moviepilot