version: '3.8'

#请修改文件名为docker-compose.yml
#自用配置，注意注释内容，参数请自行增删改，参考官方项目 https://github.com/jxxghp/MoviePilot#配置 
#插件安装目录监控，监控 /F/downloads 等挂载进容器后的下载目录，转移模式选择兼容模式

services:
  moviepilot:
    container_name: moviepilot
    image: 'jxxghp/moviepilot:latest'
    restart: unless-stopped
    ports:
      - '3002:3002'
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 000
      TZ: Asia/Shanghai
      NGINX_PORT: 3002
      SUPERUSER: 'admin'
      SUPERUSER_PASSWORD: ''
      API_TOKEN: ''
      PROXY_HOST: 'http://host.docker.internal:7890'
      DOWNLOAD_PATH: 'F:\downloads'  # Win下载器目录，必须与Win宿主下载器目录一致，否则推送下载路径报错
      DOWNLOAD_CATEGORY: true
      DOWNLOAD_SUBTITLE: true
      REFRESH_MEDIASERVER: true
      DOWNLOADER_MONITOR: false # 关闭下载器监控，否则会转移两次，路径报错
      SCRAP_METADATA: true
      TORRENT_TAG: 'MOVIEPILOT'
      LIBRARY_PATH: '/F/media'  # 媒体目录,填写容器内路径
      LIBRARY_CATEGORY: true
      TRANSFER_TYPE: 'link' # 使用硬连接
      COOKIECLOUD_HOST: ''
      COOKIECLOUD_KEY: ''
      COOKIECLOUD_PASSWORD: ''
      COOKIECLOUD_INTERVAL: 10
      USER_AGENT: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.183'
      MESSAGER: 'telegram'
      TELEGRAM_TOKEN: ''
      TELEGRAM_CHAT_ID: 
      TELEGRAM_USERS: 
      TELEGRAM_ADMINS: 
      DOWNLOADER: 'qbittorrent'
      QB_HOST: 'host.docker.internal:8990'
      QB_USER: 'admin'
      QB_PASSWORD: 'adminadmin'
      MEDIASERVER: 'jellyfin'
      MEDIASERVER_SYNC_INTERVAL: 6
      JELLYFIN_HOST: 'host.docker.internal:8096'
      JELLYFIN_API_KEY: ''
      AUTH_SITE: 'iyuu'
      IYUU_SIGN: ''
      BIG_MEMORY_MODE: true
    volumes:
      - ./config:/config
      - ./moviepilot:/moviepilot
      - /F:/F  #建议直接挂载磁盘，否则-1报错
